version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  variables:
    STAGING_URL: http://local-www.weboftomorrow.com

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci

  build:
    commands:
      - npm run test-integration -- ${STAGING_URL}
