version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  variables:
    # STAGING_URL is set when running the build (see CloudFrontStaging resource)
    STAGING_URL: http://local-www.weboftomorrow.com
    # GIT_BRANCH is typically set by the GitBranchToBuildFrom parameter value.
    GIT_BRANCH: release

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - git checkout $GIT_BRANCH
      - npm ci

  build:
    commands:
      - npm run test-integration -- ${STAGING_URL}
