version: 0.2

env:
  shell: bash
  git-credential-helper: yes

  parameter-store:
    EXAMPLE_PUBLIC_KEY: /weboftomorrow/example_public_key
    EXAMPLE_SECRET_KEY: /weboftomorrow/example_secret_key

  variables:
    GIT_BRANCH: release

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - git checkout $GIT_BRANCH
      - git submodule update --init --recursive
      - apt-get update
      - apt-get --yes install imagemagick
      - apt-get --yes install sqlite3
      - apt-get --yes install libpq-dev
      - apt-get --yes install python-psycopg2
      - apt-get --yes install zip
      - npm ci

  pre_build:
    commands:
      - python3 -m venv .
      - source bin/activate
      - echo "EXAMPLE_PUBLIC_KEY=$EXAMPLE_PUBLIC_KEY" > .env;
      - echo "EXAMPLE_SECRET_KEY=$EXAMPLE_SECRET_KEY" >> .env;
  build:
    commands:
      - npm run build
      - make ENVIRONMENT=production
      - make dist
      - ./bin/static.sh www.weboftomorrow.com-*.tar.gz
  post_build:
    finally:
      - echo "Creating source.zip"
      - TMP_STATICZIP_DIR=$(mktemp -d);
      - mv static.zip $TMP_STATICZIP_DIR
      - git clean -dx -f
      - zip -r source.zip .
      - mv ${TMP_STATICZIP_DIR}/static.zip ./

artifacts:
  files:
    - static.zip
    - source.zip
